### ISSUE TITLE
Add GLM into MCMC and EM

### ISSUE THREAD

**Issue by abrahamnunes** [abrahamnunes/fitr#32]
The EMFit code by Quentin Huys includes ability to have regressors incorporated in the EM procedure. I will look further at his code and incorporate this into `fitr.EM()`.

I will also look into building this into  MCMC models.

**Comment by ARudiuk** [comment]
@abrahamnunes are you still interested in this or should we switch focus and close this issue?

**Comment by abrahamnunes** [comment]
So not iterested.
