### ISSUE TITLE
Implement tasks

### ISSUE THREAD

**Issue by ARudiuk** [abrahamnunes/fitr#34]

**Comment by abrahamnunes** [comment]
Four armed bandit would be easy. Just use `tasks.bandit(narms=4).simulate(...)`

**Comment by ARudiuk** [comment]
- [ ] bandit updated
- [ ] twostep task
- [ ] iowa

**Comment by abrahamnunes** [comment]
- [ ] Add Stan models for bandit updated
- [ ] Add MBMF models for twostep task 
- [ ] All twostep task models require Stan code

**Comment by ARudiuk** [comment]
I think these ideas are too old, what do you think of closing @abrahamnunes
