### ISSUE TITLE
Tests for New Code

### ISSUE THREAD

**Issue by ARudiuk** [abrahamnunes/fitr#67]
Once the new code is in this issue will be used to discuss the development of tests. 

This issue closes #10

**Comment by ARudiuk** [comment]
check out docstring

**Comment by abrahamnunes** [comment]
Ive started writing tests the way we used to. doctests is a bit cumbersome in my view, and would be difficult to account for some of the larger tests that will have to be done with the model-fitting routines.

Can I close this or were you thinking of talking about more tests in general here?

**Comment by ARudiuk** [comment]
I think it's fair to close this for now!
