### ISSUE TITLE
Update Readme

### ISSUE THREAD

**Issue by ARudiuk** [abrahamnunes/fitr#68]
The readme needs to be cleared up. I'm thinking a couple things are important for this.

1. Change the format from rst to md
2. Remove clutter from headers
3. Adopt a more standardized format

Any thoughts @abrahamnunes 

This should also cover the old issue #11 which should be fixed.

**Comment by abrahamnunes** [comment]
With respect to standardized format, I'm a fan of simply 

- What the package is
- How to install 
- Simple working example (if it's short) 
- Where to look for documentation
- Where to look for contribution guidelines (probably too early to do this though)
- How to cite

Would be nice to have a logo of some sort. 

What are your thoughts @ARudiuk ?

**Comment by ARudiuk** [comment]
I mostly agree with that @abrahamnunes  I would just add some things

- What the package is
- How to install
- How to run tests
- Simple working example (if it's short)
- Where to look for documentation
- Where to look for contribution guidelines (probably too early to do this though)
- Authors
- License
- How to cite
